global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'ntfy-critical'
  routes:
    - match:
        severity: critical
      receiver: ntfy-critical
    - match:
        severity: warning
      receiver: ntfy-warning
    - match:
        severity: info
      receiver: ntfy-info

receivers:
  - name: 'ntfy-critical'
    webhook_configs:
      - url: 'https://ntfy.sh/swarm-6c7d3e5bf293-alerts?title=CRITICAL:%20Swarm%20Alert&priority=urgent&tags=rotating_light'
        send_resolved: true

  - name: 'ntfy-warning'
    webhook_configs:
      - url: 'https://ntfy.sh/swarm-6c7d3e5bf293-alerts?title=WARNING:%20Swarm%20Alert&priority=high&tags=warning'
        send_resolved: true

  - name: 'ntfy-info'
    webhook_configs:
      - url: 'https://ntfy.sh/swarm-6c7d3e5bf293-alerts?title=INFO:%20Swarm%20Alert&priority=default&tags=information_source'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
